tap "homebrew/cask"
brew "git"
brew "colordiff"
brew "composer"
# brew "git"
brew "grip"
cask "brave-browser"
cask "cyberduck"
cask "dropbox"
cask "fastrawviewer"
cask "flux"
cask "iterm2"
cask "keepassx"
cask "slack"
cask "zoom"
cask "nordvpn"
