include theme/onedark.conf
include font/firacode.conf

font_size 14

hide_window_decorations titlebar-only

startup_session session/startup_session.conf

resize_draw_strategy blank

allow_remote_control socket-only

listen_on unix:/tmp/kitty

background_opacity 0.9
background_blur 30

# BEGIN_KITTY_FONTS
font_family      family='FiraCode Nerd Font Mono' postscript_name=FiraCodeNFM-Reg
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
